### ISSUE TITLE
Spanish text for homepage

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#100]
After we have a phone number, the text should be something like this:

"Las inscripciones para el torneo de primavera comenzarán pronto. Llama al xxx-xxx-xxxx para más información en español."

If that's too much text, a shorter version is this: 

"El torneo de primavera comenzará pronto. Llama al xxx-xxx-xxxx para más información en español."

(Translation by Alfonso.)

**Comment by kostajh** [comment]
Ok, let me know when there's a number to put up there.
