### ISSUE TITLE
TO DO: Update brackets 

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#102]
- Show MVFC, Real Durham and Motorco in their respective finals slots.

- Show Hustle and Flow v. Pitbulls in the third-place game

- Show DireWolfpack in the third-place game (D2)

- Is it reasonable to make the four-team consolation bracket appear? The Consolation games are:

AU-Durham Monday
Minions-Durham Thursday

Regulators-Esemplastic Power
Green Street Elite-Muchos Nachos

**Comment by kostajh** [comment]
Not making the consolation bracket appear. The rest is up there.
