### ISSUE TITLE
registration instructions in Spanish

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#107]
This text should appear early in the registration instructions. It says, "if you want to register an entire team, the cost is $600. Call or send a text to xxx... for more information."

The number is Alfonso's Google Voice number.

Si quieren registrar al equipo entero, el coste es de $600. Llame o escribe un texto al 919-937-2109 para mas información"

**Comment by kostajh** [comment]
@davidfellerath what is the phone number?

**Comment by kostajh** [comment]
@davidfellerath does this need to appear anywhere in particular, or can you just add it to `/futsal/registration`?
