### ISSUE TITLE
Style /posts

### ISSUE THREAD

**Issue by AnneTee** [durhamatletico/durhamatletico-cms#11]

**Comment by kostajh** [comment]
@AnneTee sorry, meant to make a PR for the commit above. Let me know what you think -- I was thinking we could use the cards motif a la Savas Blabs, but open to other ideas too.

**Comment by AnneTee** [comment]
@kostajh these latest commits have thrown me into config import hell. Maybe we can take a look at this together. I'm getting the following error when I try to import config:

```
Drupal\Core\Config\ConfigImporterException: There were errors validating the  [error]
config synchronization. in Drupal\Core\Config\ConfigImporter->validate() (line
730 of
/Applications/MAMP/htdocs/da-drupal/core/lib/Drupal/Core/Config/ConfigImporter.php).
The import failed due for the following reasons:                              [error]
Entities exist of type <em class="placeholder">Content</em> and <em
class="placeholder">Content type</em> <em class="placeholder">Team</em>. These
entities need to be deleted before importing.
```

I tried on a clean DB (pulled from the DB dump on Pantheon from today), same issue.

**Comment by kostajh** [comment]
@AnneTee hmm, it looks like I was a bit hasty in that commit as all I did was delete things with it! Did you import the DB from production?
