### ISSUE TITLE
Failing tests on SCSS lint

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#120]
see for example https://circleci.com/gh/durhamatletico/durhamatletico-cms/253

the `!important` declaration apparently isn't allowed, but is also needed for the dropdown menus to work. Any ideas?

**Comment by AnneTee** [comment]
@kostajh You can disable and re-enable rules [like I've done for the ID Selector rule here](https://github.com/durhamatletico/durhamatletico-cms/blob/master/themes/atletico/sass/layouts/_layout-node.scss#L10). I try to include a comment on why I need to violate a rule, such as `Override default Drupal styles` or something. Hope that helps!

**Comment by kostajh** [comment]
Ah, good call, thanks @AnneTee!
