### ISSUE TITLE
Site not completely updated on Firefox

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#121]
I recently started using Firefox. The schedule isn't completely updated there. Last Thursday's games are still showing as "upcoming." Furthermore, the nav buttons don't seem to work once you click to the next week. Jonah Berger encountered this nav issue, too. I didn't ask him which browser he was using. 

However, the standings are complete. 

![screenshot 2016-05-14 15 57 17](https://cloud.githubusercontent.com/assets/10568034/15270390/a2684242-19ec-11e6-8e8b-e091d8aa2941.png)

**Comment by kostajh** [comment]
@davidfellerath are you still seeing the May 12 games? This is probably a page cache thing -- were you logged in when you took this screenshot?

The nav buttons for next week bug I know about, but it needs its own issue.

**Comment by davidfellerath** [comment]
I can't remember if I was logged in, but the schedule is displaying correctly.
