### ISSUE TITLE
Nav buttons are wonky

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#122]
Not working on Firefox, anyway.

**Comment by kostajh** [comment]
I need a bit more info to be able to do anything about this

**Comment by davidfellerath** [comment]
I thought you were familiar with this issue. Anyway, the "previous" and "next" buttons don't work once I've clicked the "more" button on the /futsal page.

![screenshot 2016-05-15 23 17 00](https://cloud.githubusercontent.com/assets/10568034/15279531/669feaaa-1af3-11e6-88c1-53f5c3614180.png)

**Comment by kostajh** [comment]
Gotcha. Yes, now I know what you're talking about. "Nav buttons" was a little vague :-)
