### ISSUE TITLE
Stripe-compatible POS mobile app

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#125]
Could you recommend one of these third-party apps for me to install on my Android tablet? (FYI, I use a VPN on it.)

[https://stripe.com/docs/integrations#card-readers](https://stripe.com/docs/integrations#card-readers)

**Comment by kostajh** [comment]
@davidfellerath can you tell me a bit more about what you would like to do this, and if the purchases made via POS have to synchronize with any data on the website?

**Comment by davidfellerath** [comment]
I'd like to have the ability to take CC payments on site. It'd be nice if I
didn't have to keep track of a swipe thingie, and could instead just scan
the card with the tablet.

As for syncing with the website... I guess I could manually update the
paying player's payment status on the website.

However, we were talking about creating a form to use on site in order to
capture unregistered players' info. Perhaps this form could be synced to
Stripe and the website.

On Sun, Jun 12, 2016 at 1:52 PM, Kosta Harlan <notifications@github.com>
wrote:

> @davidfellerath <https://github.com/davidfellerath> can you tell me a bit
> more about what you would like to do this, and if the purchases made via
> POS have to synchronize with any data on the website?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/durhamatletico/durhamatletico-cms/issues/125#issuecomment-225450757>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKFBYlP1yk3SzmSKyda1mrUn7OSYdm2Pks5qLEdIgaJpZM4IzxX4>
> .
>



-- 
David Fellerath, freelance writer

Manager, Durham Atlético, LLC
durhamatletico.com
@DurhamAtletico

919-260-0245
@DavidFellerath

**Comment by kostajh** [comment]
OK. It sounds to me like this is what we want:

- A form that you can load on your tablet, say at `https://www.durhamatletico.com/register/guest`
- The form contains basic info you want on a player (Name, Phone, Email)
- You can type in a Credit Card number and exp date and charge the player
- When submitted, the form creates/updates a user and creates a link between that user account and the game they played in [lot of development to put in place for that bit]
