### ISSUE TITLE
Name change for Brazil

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#139]
Rolando's young lions revolted against their Siegfried. They approached me and said, "We don't like our name. We don't want to be Brazil." 

They said "Germany... no, we speak Spanish. We will be Alemania."

Rolando showed up, recoiled when I said they would be Alemania. He and his players compromised and settled on "Italia." Too bad, I liked "Alemania."

I made the changes where I was able to, but the standings still say Brazil.

**Comment by kostajh** [comment]
@davidfellerath you have to look a little farther down the form, and edit the "Abbreviation" field. I've gone ahead and done that. Also, I set the title to "Italy" -- the Spanish translation can use "Italia"

**Comment by davidfellerath** [comment]
I prefer "Italia." That's what they said -- just like they'd specified
"Alemania" rather than "Germany."
