### ISSUE TITLE
Set up CircleCI, Behat, PhpSpec and friends

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#15]

**Comment by kostajh** [comment]
@AnneTee `scss-lint` is failing, but we might want to adjust what we're linting. Let me know if I should adjust any of the variables (see `circle.yml` for the files being tested).

**Comment by kostajh** [comment]
@AnneTee I'm inclined to disable `scss-lint` tests altogether. What do you think?

**Comment by AnneTee** [comment]
@kostajh I actually got it working earlier today. Working on a bug on the mobile view of /posts then I'll push it up.
