### ISSUE TITLE
Style footer

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#16]
I think these can flow left to right, instead of stacked. It would be nice to have a second row to the footer where we can put copyright info for DA as well.

- [x] Footer menu items (room for ~5 or so)
- [x] Copyright notice
- [x] A sentence or two about Durham Atletico, mailing address, etc

**Comment by AnneTee** [comment]
Also should make the footer sticky

**Comment by AnneTee** [comment]
@kostajh Can you provide me with text for the two remaining bullets?

**Comment by kostajh** [comment]
Sure!

## Copyright

`Copyright © 2015 -- Present, Durham Atletico`

## Mailing Address

Durham Atletico
201 W Main Street, Durham, NC 27701

**Comment by davidfellerath** [comment]
@kostajh Should we really use this address? I think it's too soon for this to be our permanent mailing address. We'll need to raise more money.

Otherwise: 817 Nancy Street, Durham, NC 27701

**Comment by kostajh** [comment]
just to note, it's not a mailing address. You can't receive mail here unless you're in an office.

David Fellerath writes:

> @kostajh Should we really use this address? I think it's too soon for this to be our permanent mailing address. We'll need to raise more money.
>
> Otherwise: 817 Nancy Street, Durham, NC 27701
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/durhamatletico/durhamatletico-cms/issues/16#issuecomment-160659428

--
@kostajh | kosta@kostaharlan.net

**Comment by davidfellerath** [comment]
What other comment were you thinking I wanted to make? A line or two about Durham Atletico's mission?

**Comment by davidfellerath** [comment]
Follow us on Facebook and Twitter!

Links:
www.facebook.com/durhamatletico
https://twitter.com/DurhamAtletico

**Comment by kostajh** [comment]
@AnneTee one minor issue - the FB/Twitter icons aren't showing up, could you take a look when you have a moment? Thanks!

**Comment by AnneTee** [comment]
@kostajh I see them on the production site, are you still not seeing them?
