### ISSUE TITLE
Standings problem - Division 2

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#166]
Both Olympiakos and Black Magicians are showing only one game played. I think this is a new problem, introduced when I updated last night's result.

**Comment by kostajh** [comment]
This was the problem

<img width="554" alt="image" src="https://user-images.githubusercontent.com/208893/31175402-3425c904-a8dd-11e7-882d-47dac4840017.png">

The game was referencing division 1
