### ISSUE TITLE
Registration form glitch

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#187]
Where the registrant is prompted to make a selection for "Registration for" either futsal or soccer, it is not showing any values. 

I must have introduced this error when trying to clean up the competition nodes. I'm sorry.

**Comment by kostajh** [comment]
@davidfellerath make sure the three competition nodes are referenced from the Winter 2018 season node. Make sure all three competition nodes have the checkbox ticked for "Open for registration" and that the default amount is `7000`.

**Comment by davidfellerath** [comment]
Aha, looks like the checkbox has been unchecked.  Updating now.
