### ISSUE TITLE
MVP of custom theme based on old Durham Atletico site styles

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#2]
@AnneTee I started working on this (see #1) but it's barely existent. I was thinking the new site theme would be more or less similar to the old one (https://github.com/durhamatletico/durhamatletico.github.io) but open to ideas & suggestions.

Let me know if you have suggestions!

**Comment by kostajh** [comment]
@annetee I should note, the logo files are here https://github.com/durhamatletico/durham-atletico-assets

Generally the new site theme could be based off the logo colors. The old static site pre-dated the logos, so that's why the old site colors don't really match up well.

**Comment by AnneTee** [comment]
Thanks @kostajh, let me know what you think of the color scheme so far. Or if you have any problems getting the theme to display properly.
