### ISSUE TITLE
Game content type

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#31]
- [x] Home team
- [x] Away team
- [x] Date
- [x] Kick off time
- [x] Venue
- [x] Status (not yet played, postponed, played)
- [x] Division
- [x] Season
- [x] Referee (text or entity ref?)

**Comment by kostajh** [comment]
@davidfellerath these are the proposed fields for the `Game` content type. As you can see it will serve both as a placeholder for the schedule, and we'll edit the same Game node after a match to update information about the winner, score, etc etc. Any other fields that should be added here?

**Comment by davidfellerath** [comment]
Are "points" and individual goal scorers are going to be calculated or
recorded elsewhere?
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Wed, Dec 30, 2015 at 12:34 PM, Kosta Harlan <notifications@github.com>
wrote:

> @davidfellerath <https://github.com/davidfellerath> these are the
> proposed fields for the Game content type. As you can see it will serve
> both as a placeholder for the schedule, and we'll edit the same Game node
> after a match to update information about the winner, score, etc etc. Any
> other fields that should be added here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/durhamatletico/durhamatletico-cms/issues/31#issuecomment-168040958>
> .
>



-- 
David Fellerath, freelance writer

Manager, Durham Atlético, LLC
durhamatletico.com
@DurhamAtletico

919-260-0245
@DavidFellerath

**Comment by kostajh** [comment]
@davidfellerath see https://github.com/durhamatletico/durhamatletico-cms/issues/28 for goals. Those will be added separately
