### ISSUE TITLE
Build out registration system

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#52]
Seems sensible to start this with a spec, so here goes:

# Overview

1. Users register for *accounts* on the Drupal site.
2. An account allows them to register for a *league*.
3. Registering for a league allows them to pay.
4. DA admins can modify the registration to link up the player with a team, mark the registration as "processed"

### User registration

This is handled by Drupal core. We already have fields for data that won't ever change about the user (their birthdate, name, etc). Users fill out the registration form and are sent a login URL via e-mail, at which point they can change their password and login.

### Register for a league

1. After logging in, next to "My Account", a new menu item for "Register for a league" shows up.
2. Clicking "Register for a league" is a link to `node/add/registration`

The `registration` content type contains fields for:

1. Team name (type in the name of a team). This is *not* an entity reference field
2. Team (entity reference, hidden). This is updated manually by DA admins after the user has paid.
3. Misc other questions
4. League (radio button), options for which league to register for (e.g. division 1, division 2)
5. Payment amount ($60, hidden from user). This field is hidden from the user so they can't edit it.

Clicking "Save" (we'll alter the text to say "Register") will save the node.

We need to implement settings so user can (1) create only one registration node and (2) can only view their node. (hook node access?)

### Payment

After saving, user will see their registration and the rendered Stripe payment button.

After successful payment, balance due is set to $0, our module listens on the entity update hook for a change, and sends an email to DA admins that their registration needs to be processed.

### Processing

DA admins can update the registration node for that player and link them with a team.

**Comment by davidfellerath** [comment]
Hmm. How is it going to work, players deciding whether to register for first or second division? What I imagined was registrants encountering a list of teams. Some of these teams will be essentially closed to new players. Like Motorco or Regulators, who recruit their own players. Perhaps the teams should be ID'd in the following fashion: "Closed to new players", "by invitation," "looking for players."

A team like Motorco, where Josh or Daniel is likely to simply write a check for $500, would be "closed to new players." A team like the Regulators, whose captain wants players to self-register, would be "by invitation." 

Just thinking aloud here. I don't know if we want to allow players to select their division. I'd rather that declared free agents self-assess (which could include a stated preference for first or second division), and then we could make assignments.

**Comment by kostajh** [comment]
@davidfellerath to avoid lots of custom programming work, step 2 is going to be a bit freeform. We can show a list of teams, but the user will enter a team name into a free text field. From there, it's up to us to manually process that and "link" it in the backend system with an actual team / division. As part of step 2, we'll ask them their skill level, what division they prefer to play in, etc etc.

**Comment by kostajh** [comment]
Note that for teams where one person is paying $500, *all* players will still be required to do step 1.

**Comment by davidfellerath** [comment]
OK
