### ISSUE TITLE
Update registration for T-shirts

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#66]
@kostajh 

1. Male shirt or female shirt?

2. The size options are: 
S
M
L
XL
2XL
3XL.

3. Uniform numbers should be one or two digits.

The shirt will be a 4.5 oz sweat-wicking, 100 percent polyester shirt.

**Comment by kostajh** [comment]
@davidfellerath should these questions be on (1) the user profile, or (2) the individual registration that a user creates for a league? The first one is for all time, the second one is specific to a particular league/season/team. Probably the second one makes sense, but wanted to check with you.

**Comment by davidfellerath** [comment]
I think it should be seasonal, yes.

**Comment by kostajh** [comment]
@davidfellerath this is on the live site now.
