### ISSUE TITLE
Implement right sidebar

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#7]

**Comment by AnneTee** [comment]
@kostajh Right now this is showing the recent posts block. I know eventually you want sponsor logos to show up on a rotating basis. Anything else you want in the sidebar for now? The winter 2016 block would make sense I think.

**Comment by kostajh** [comment]
I'm not sure yet. The winter 2016 block kind of has a lot for a sidebar item. Could we do a simple call to action block the directs people to http://eepurl.com/bxLYG9 ?
