### ISSUE TITLE
Create for the logo

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#75]
Could we find an appropriate place to credit Harbor Studio Design for the creation of the Durham Atletico logo? Perhaps in text at the bottom, something like "The Durham Atlético logo was created by Brendan Ward of Harbor Studio."? (With a link to http://www.studioharbor.com/)

**Comment by kostajh** [comment]
Would adding this info to the Credits page suffice?

On Tue, Dec 15, 2015, at 09:11 AM, David Fellerath wrote:
> Assigned #75[1] to @kostajh[2].


> — Reply to this email directly or view it on GitHub[3].


>



Links:

  1. https://github.com/durhamatletico/durhamatletico-cms/issues/75
  2. https://github.com/kostajh
  3. https://github.com/durhamatletico/durhamatletico-cms/issues/75#event-492258206

**Comment by davidfellerath** [comment]
That's probably fine. This is something I'm requesting on my own initiative, not a request from Brendan. I can add it to the credits page, then.
