### ISSUE TITLE
Export player names and birthdates

### ISSUE THREAD

**Issue by davidfellerath** [durhamatletico/durhamatletico-cms#76]
1. need to supply roster with names and birthdates to insurer.

2. can it be sortable in some way so that when I send periodic updates to the insurer I can easily filter the newest people?

**Comment by kostajh** [comment]
@davidfellerath you got everything you need for this?

**Comment by davidfellerath** [comment]
I'm not sure--can you tell me how to view this info?

thanks
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Wed, Dec 30, 2015 at 9:03 PM, Kosta Harlan <notifications@github.com>
wrote:

> @davidfellerath <https://github.com/davidfellerath> you got everything
> you need for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/durhamatletico/durhamatletico-cms/issues/76#issuecomment-168110347>
> .
>



-- 
David Fellerath, freelance writer

Manager, Durham Atlético, LLC
durhamatletico.com
@DurhamAtletico

919-260-0245
@DavidFellerath

**Comment by kostajh** [comment]
https://www.durhamatletico.com/admin/registration/names-emails

David Fellerath writes:

> I'm not sure--can you tell me how to view this info?
>
> thanks
> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
> This
> email has been sent from a virus-free computer protected by Avast.
> www.avast.com
> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
> <#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>
> On Wed, Dec 30, 2015 at 9:03 PM, Kosta Harlan <notifications@github.com>
> wrote:
>
>> @davidfellerath <https://github.com/davidfellerath> you got everything
>> you need for this?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/durhamatletico/durhamatletico-cms/issues/76#issuecomment-168110347>
>> .
>>

-- 
@kostajh | kosta@kostaharlan.net
