### ISSUE TITLE
Nicely formatted view for a game node

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#82]
the Guardian has a nice example we can mimic: http://www.theguardian.com/football/match/2016/jan/06/napoli-v-torino

**Comment by kostajh** [comment]
@AnneTee any interest in taking this on?

**Comment by AnneTee** [comment]
@kostajh Sure, I should have time to work on this and #81 this weekend (probably Monday)

**Comment by AnneTee** [comment]
@kostajh I just merged in some commits to improve the game node display. One thing I didn't get working was the jersey color - I'm not sure of the best way to access this field. Let me know if you have any feedback on the theming end :octopus:
