### ISSUE TITLE
Jersey colors not working on all pages

### ISSUE THREAD

**Issue by AnneTee** [durhamatletico/durhamatletico-cms#88]
If you use the pager on the game tables on /futsal, the jersey colors are all defaulting to white.

**Comment by kostajh** [comment]
Ah, that's annoying. I bet disabling AJAX will fix.

**Comment by kostajh** [comment]
Or adjusting the snippet of JS so it fires after an AJAX request. I'll look into it.

**Comment by AnneTee** [comment]
Disabling AJAX does fix it, but obviously it'd be nice not to disable it if there's a better solution

**Comment by kostajh** [comment]
Fixed by disabling AJAX.
