### ISSUE TITLE
Use responsive table settings

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#92]
See this from Bartik

```
/**
 * Responsive tables.
 */
@media screen and (max-width: 37.5em) { /* 600px */
  th.priority-low,
  td.priority-low,
  th.priority-medium,
  td.priority-medium {
    display: none;
  }
}
@media screen and (max-width: 60em) { /* 920px */
  th.priority-low,
  td.priority-low {
    display: none;
  }
}
```

**Comment by kostajh** [comment]
Once this is implemented, this should result in most of the columns in the standings table vanishing for small viewports. I'm using the Views table settings to specify which columns to hide.

**Comment by kostajh** [comment]
@AnneTee If I append the lines above to `_games_landing.scss`, the standings block on the `/futsal` page looks good on mobile as only three columns are shown. But, I'm not sure how to rewrite it to fit the framework we're using. Any tips? I would have thought `@include media($small)` would be it, but that doesn't seem to work right.

**Comment by AnneTee** [comment]
@kostajh `media($small)` means for screen sizes larger than `$small`, do this. So we need to switch the logic around to use the `media` mixin. I just got it working and will open a PR. We could play around with the screen size at which the low priority items don't display.
