### ISSUE TITLE
Add Instagram logo to home page footer

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico-cms#98]
Next to twitter & facebook. Account name is `durhamatletico`.

**Comment by kostajh** [comment]
@AnneTee I must have done something wrong. When you have a moment could you take a look?

**Comment by AnneTee** [comment]
@kostajh The icon name is `fa-instagram`, not `fa-instagram-square`. [This is extremely helpful!](https://fortawesome.github.io/Font-Awesome/cheatsheet/)

Also, have you considered updating the copy above it that says "Follow us on Facebook and Twitter?" Seems a little weird now that you're adding another option.

**Comment by kostajh** [comment]
:dizzy_face: thanks!
